const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "1.0.0",
        title: "Project 3 Backend",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3001",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Auth",
            "description": "Endpoints"
        },
        {
            "name": "Inventory",
            "description": "Endpoints"
        },
        {
            "name": "Menu",
            "description": "Endpoints"
        },
        {
            "name": "Orders",
            "description": "Endpoints"
        }
    ],
    definitions: {
        InventoryItem: {
            ingredient_name: "Falafel",
            quantity: 100
        },
        MenuItem: {
            id: 2,
            name: "Gyro",
            quantity: 100,
            price: 2.85
        }, 
        OrderItems: {
            items : [
                {
                    isCombo   : "false",
                    starterId : "",
                    baseId    : "3",
                    proteinId : "4"
                },
                {
                    isCombo   : "",
                    starterId : "1",
                    baseId    : "",
                    proteinId : ""
                }
            ]
        }
    }
}

const outputFile = './swagger-output.json'
const endpointsFiles = ['./routes/auth.js', './routes/inventory.js', './routes/menu.js', './routes/orders.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app')           // Your project's root file
})